### ISSUE TITLE
Comb over README for new React rewrite

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-iq-chrome-extension#138] opened 2021-05-05 23:41 UTC
The old readme was copied in, it will likely need a lot of adjustments to reflect the new reality.

To finish this issue up, take a look at the README, make new screenshots, and document usage best you can!

**Comment by madpah** [comment] 2023-05-19 13:06
Closing as duplicate of #131

**Closed by madpah** 2023-05-19 13:06 UTC
Labels: enhancement, help wanted, good first issue
