### ISSUE TITLE
add support for Java - Maven new https://central.sonatype.com/ (that will replace search.maven.org)

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/nexus-iq-chrome-extension#266] opened 2023-05-19 14:06 UTC
https://central.sonatype.com/ will supercede https://search.maven.org/ #231

**Comment by madpah** [comment] 2023-05-31 07:35
Duplicate of #201 which is included in 2.0.0 release.

**Comment by ctownshend** [comment] 2023-06-06 06:21
Fixed in 2.x

**Closed by ctownshend** 2023-06-06 06:21 UTC
Labels: duplicate
